export const products = [
  {
    id: "1",
    name: "Lọc gió động cơ Air Filter – Chevrolet Colorado, Trailblazer (52046262)",
    price: 329000,
    sale_price: 299000,
    percent_discount: 10,
    img: "M1.png",
  },
  {
    id: "2",
    name: "Lọc gió động cơ Air Filter – Chevrolet Colorado, Trailblazer (52046262)",
    price: 329000,
    sale_price: 299000,
    percent_discount: 10,
    img: "M2.png",
  },
  {
    id: "3",
    name: "Lọc gió động cơ Air Filter – Chevrolet Colorado, Trailblazer (52046262)",
    price: 329000,
    sale_price: 299000,
    percent_discount: 10,
    img: "M3.png",
  },
  {
    id: "4",
    name: "Lọc gió động cơ Air Filter – Chevrolet Colorado, Trailblazer (52046262)",
    price: 329000,
    sale_price: 299000,
    percent_discount: 10,
    img: "M4.png",
  },
  {
    id: "5",
    name: "Lọc gió động cơ Air Filter – Chevrolet Colorado, Trailblazer (52046262)",
    price: 329000,
    sale_price: 299000,
    percent_discount: 10,
    img: "M1.png",
  },
  {
    id: "6",
    name: "Lọc gió động cơ Air Filter – Chevrolet Colorado, Trailblazer (52046262)",
    price: 329000,
    sale_price: 299000,
    percent_discount: 10,
    img: "M2.png",
  },
  {
    id: "7",
    name: "Lọc gió động cơ Air Filter – Chevrolet Colorado, Trailblazer (52046262)",
    price: 329000,
    sale_price: 299000,
    percent_discount: 10,
    img: "M3.png",
  },
  {
    id: "8",
    name: "Lọc gió động cơ Air Filter – Chevrolet Colorado, Trailblazer (52046262)",
    price: 329000,
    sale_price: 299000,
    percent_discount: 10,
    img: "M4.png",
  },
  {
    id: "9",
    name: "Lọc gió động cơ Air Filter – Chevrolet Colorado, Trailblazer (52046262)",
    price: 329000,
    sale_price: 299000,
    percent_discount: 10,
    img: "M1.png",
  },
  {
    id: "10",
    name: "Lọc gió động cơ Air Filter – Chevrolet Colorado, Trailblazer (52046262)",
    price: 329000,
    sale_price: 299000,
    percent_discount: 10,
    img: "M2.png",
  },
  {
    id: "11",
    name: "Lọc gió động cơ Air Filter – Chevrolet Colorado, Trailblazer (52046262)",
    price: 329000,
    sale_price: 299000,
    percent_discount: 10,
    img: "M3.png",
  },
  {
    id: "12",
    name: "Lọc gió động cơ Air Filter – Chevrolet Colorado, Trailblazer (52046262)",
    price: 329000,
    sale_price: 299000,
    percent_discount: 10,
    img: "M4.png",
  },
  {
    id: "13",
    name: "Lọc gió động cơ Air Filter – Chevrolet Colorado, Trailblazer (52046262)",
    price: 329000,
    sale_price: 299000,
    percent_discount: 10,
    img: "M1.png",
  },
  {
    id: "14",
    name: "Lọc gió động cơ Air Filter – Chevrolet Colorado, Trailblazer (52046262)",
    price: 329000,
    sale_price: 299000,
    percent_discount: 10,
    img: "M2.png",
  },
  {
    id: "15",
    name: "Lọc gió động cơ Air Filter – Chevrolet Colorado, Trailblazer (52046262)",
    price: 329000,
    sale_price: 299000,
    percent_discount: 10,
    img: "M3.png",
  },
  {
    id: "16",
    name: "Lọc gió động cơ Air Filter – Chevrolet Colorado, Trailblazer (52046262)",
    price: 329000,
    sale_price: 299000,
    percent_discount: 10,
    img: "M4.png",
  },
];

export const categories = [
  {
    id: 1,
    name: "Bộ Lọc Dầu",
    img: "/images/M5.png",
    subCategories: [
      { name: "Bộ lọc gió", img: "/images/M5.png" },
      { name: "Bộ lọc gió", img: "/images/M5.png" },
      { name: "Bộ lọc gió", img: "/images/M10.png" },
      { name: "Bộ lọc gió", img: "/images/M10.png" },
      { name: "Bộ lọc gió", img: "/images/M10.png" },
      { name: "Bộ lọc gió", img: "/images/M10.png" },
    ],
  },
  {
    id: 2,
    name: "Bộ Lọc Không Khí",
    img: "/images/M6.png",
    subCategories: [
      { name: "Bộ lọc gió", img: "/images/M10.png" },
      { name: "Bộ lọc gió", img: "/images/M10.png" },
      { name: "Bộ lọc gió", img: "/images/M10.png" },
      { name: "Bộ lọc gió", img: "/images/M10.png" },
    ],
  },
  {
    id: 3,
    name: "Bộ Lọc Nhiên Liệu",
    img: "/images/M2.png",
    subCategories: [
      { name: "Bộ lọc gió", img: "/images/M5.png" },
      { name: "Bộ lọc gió", img: "/images/M5.png" },
      { name: "Bộ lọc gió", img: "/images/M10.png" },
      { name: "Bộ lọc gió", img: "/images/M10.png" },
      { name: "Bộ lọc gió", img: "/images/M10.png" },
      { name: "Bộ lọc gió", img: "/images/M10.png" },
    ],
  },
  {
    id: 4,
    name: "Bộ Lọc Trong Cabin",
    img: "/images/M7.png",
    subCategories: [
      { name: "Bộ lọc gió", img: "/images/M8.png" },
      { name: "Bộ lọc gió", img: "/images/M5.png" },
      { name: "Bộ lọc gió", img: "/images/M8.png" },
      { name: "Bộ lọc gió", img: "/images/M8.png" },
      { name: "Bộ lọc gió", img: "/images/M8.png" },
      { name: "Bộ lọc gió", img: "/images/M8.png" },
    ],
  },
  {
    id: 5,
    name: "Bộ Lọc Không Khí",
    img: "/images/M6.png",
    subCategories: [
      { name: "Bộ lọc gió", img: "/images/M5.png" },
      { name: "Bộ lọc gió", img: "/images/M5.png" },
      { name: "Bộ lọc gió", img: "/images/M10.png" },
      { name: "Bộ lọc gió", img: "/images/M10.png" },
      { name: "Bộ lọc gió", img: "/images/M10.png" },
      { name: "Bộ lọc gió", img: "/images/M10.png" },
    ],
  },
  {
    id: 6,
    name: "Bộ Lọc Nhiên Liệu",
    img: "/images/M2.png",
    subCategories: [
      { name: "Bộ lọc gió", img: "/images/M5.png" },
      { name: "Bộ lọc gió", img: "/images/M5.png" },
      { name: "Bộ lọc gió", img: "/images/M5.png" },
      { name: "Bộ lọc gió", img: "/images/M8.png" },
      { name: "Bộ lọc gió", img: "/images/M8.png" },
      { name: "Bộ lọc gió", img: "/images/M8.png" },
    ],
  },
  {
    id: 7,
    name: "Bộ Lọc Trong Cabin",
    img: "/images/M7.png",
    subCategories: [
      { name: "Bộ lọc gió", img: "/images/M5.png" },
      { name: "Bộ lọc gió", img: "/images/M5.png" },
      { name: "Bộ lọc gió", img: "/images/M10.png" },
      { name: "Bộ lọc gió", img: "/images/M10.png" },
      { name: "Bộ lọc gió", img: "/images/M10.png" },
      { name: "Bộ lọc gió", img: "/images/M10.png" },
    ],
  },
  {
    id: 8,
    name: "Bộ Lọc Trong Cabin",
    img: "/images/M7.png",
    subCategories: [
      { name: "Bộ lọc gió", img: "/images/M5.png" },
      { name: "Bộ lọc gió", img: "/images/M5.png" },
      { name: "Bộ lọc gió", img: "/images/M8.png" },
      { name: "Bộ lọc gió", img: "/images/M8.png" },
      { name: "Bộ lọc gió", img: "/images/M8.png" },
      { name: "Bộ lọc gió", img: "/images/M8.png" },
    ],
  },
];
